//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailNexus.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetailNexus.Resources.SharedMessages", typeof(SharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   リクエストの形式が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_InternalServer {
            get {
                return ResourceManager.GetString("Error_InternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一商品が複数行に含まれています。数量を変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PurchaseOrder_DuplicateProduct {
            get {
                return ResourceManager.GetString("PurchaseOrder_DuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一商品が複数行に含まれています。数量を変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreRequest_DuplicateProduct {
            get {
                return ResourceManager.GetString("StoreRequest_DuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼元と依頼先は異なる店舗を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreRequest_SameStore {
            get {
                return ResourceManager.GetString("StoreRequest_SameStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は英字{1}〜{2}文字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_AlphaRange {
            get {
                return ResourceManager.GetString("Validation_AlphaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は数字のみ入力できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_DigitsOnly {
            get {
                return ResourceManager.GetString("Validation_DigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}は既に使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_Duplicate {
            get {
                return ResourceManager.GetString("Validation_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスの形式が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_EmailFormat {
            get {
                return ResourceManager.GetString("Validation_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された{0}が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_EntityNotFound {
            get {
                return ResourceManager.GetString("Validation_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された{0}が存在しないか、無効になっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_EntityNotFoundOrInactive {
            get {
                return ResourceManager.GetString("Validation_EntityNotFoundOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}桁で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ExactLength {
            get {
                return ResourceManager.GetString("Validation_ExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_GreaterThan {
            get {
                return ResourceManager.GetString("Validation_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}IDリストに重複があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ListDuplicate {
            get {
                return ResourceManager.GetString("Validation_ListDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しない{0}IDが含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ListInvalidIds {
            get {
                return ResourceManager.GetString("Validation_ListInvalidIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を1行以上入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ListMinCount {
            get {
                return ResourceManager.GetString("Validation_ListMinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_MinValue {
            get {
                return ResourceManager.GetString("Validation_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は数字とハイフン（-）のみ入力できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_PhoneFormat {
            get {
                return ResourceManager.GetString("Validation_PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
